[book]
authors = ["julia"]
language = "en"
multilingual = false
src = "src"
title = "julia's book"

[preprocessor.graphviz]
command = "mdbook-graphviz"
output-to-file = false # defaults to false, change to true to create SVG files instead of rendering them inline

[preprocessor.svgbob]
